student_email: ${EMAIL}
postgres_cluster:
  hosts:
  - address: ${PG_HOST}
    port: ${PG_PORT}
  user: bingo
  password: ${DB_PASSWORD}
  db_name: bingo
  ssl_mode: disable
  use_closest_node: false
