# See also:
# - https://github.com/yc-actions/yc-coi-deploy

name: Build and upload image

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          # https://docs.github.com/en/actions/learn-github-actions/variables
          registry: ${{ vars.REGISTRY }}
          username: oauth
          password: ${{ secrets.YA_OAUTH_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ vars.REGISTRY }}/${{ vars.YA_REGISTRY_ID }}/bingo:latest
          build-args: |
            EMAIL=${{ secrets.EMAIL }}
            PG_HOST=${{ vars.PG_HOST }}
            PG_PORT=${{ vars.PG_PORT }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            LOGDIR=${{ vars.LOGDIR }}
            PORT_INTERNAL=${{ vars.PORT_INTERNAL }}
